### ISSUE TITLE
Issues Setting Up: Problem with Jest tests

### ISSUE THREAD

**Issue by tigermarques** [kentcdodds/asts-workshop#7]
Hi,

I'm currently setting up the workshop, and I'm facing an issue where the unit tests on the `other\final` are not passing. However, the error message shows a strange output, because the expected and actual value do match, unless the problem is a special character (like the linebreak). A screenshot of the error is below.

![image](https://cloud.githubusercontent.com/assets/15315098/25429969/b4fdb71a-2a72-11e7-98e1-2da7276ced54.png)

I've tried running the tests with the `-u` flag to replace the snapshots. If I do this and after that rerun the tests, the problem reappears.

I'm running this on a Windows machine, so I guess the linebreak could be one of the issues. Any ideas? I've checked Jest repo for issues with \r and they indeed had issues, but those should be fixed in the version that's configured for the workshop.

Node Version: 6.10.1
Yarn Version: 0.23.2
Git Version: 2.12.2.windows.1

Thanks a lot!

**Comment by tigermarques** [comment]
I've checked that the linebreak is the problem here.

In file other\final\captains-log-1.test.js, I've chnged line 23 to become

```
const code = transpile(source).replace(/\r\n/g, '\n')
```

This makes the unit test pass for this case. Is there a way to configure the line ending at the babel generator level?

**Comment by tigermarques** [comment]
After a little more investigation, adding the `lineTerminator` option to the options passed to babel transform method also works:

```
const {code} = babel.transform(source, {
    parserOpts: {parser: recast.parse},
    generatorOpts: {generator: recast.print, lineTerminator: '\n'},
    babelrc: false,
    plugins: [captainsLog],
  })
```

Is this a good practice? Should this be incorporated into the repo, or should I work around it using any other way? I've checked the `recast` package, and it uses `require('os').EOL` for the lineTerminator default value, and therefore it's using `\r\n` on windows. And since everything else in the project uses `\n`, the problem arises when comparing the snapshots.

**Comment by kentcdodds** [comment]
Thanks for reporting this. Could you try deleting the repository and trying over again? I added a `.gitattributes` to force everyone to have the same lineTerminators and I think that should fix the issue. If not, then I'll try your solution. Thank you!

**Comment by tigermarques** [comment]
I've tried to clone and run the setup command again, and it still fails. I don't think the problem is with the js files having the EOL as `\r\n`. I've set up my git to preserve whatever line terminators come from the remote and my text editor to use `\n`. And I've checked that all my files have the line terminator set correctly to `\n`. The problem comes up when running the `babel.transform` command, which will at runtime use the `recast.print` function to generate the code, which in turns [uses the OS line terminator by default](https://github.com/benjamn/recast/blob/master/lib/options.js). The way to override this behavior is to explicitly set the `lineTerminator` option in the transform command.

**Comment by kentcdodds** [comment]
Cool, thanks for giving it a try, I'll apply your fix! Could you pull and try again? Thanks a ton!

**Comment by tigermarques** [comment]
Just tried it, and works like a charm. Thanks a lot! Looking forward to the workshop :)

PS: I've checked, and the issue actually seems to come from Jest, which writes the snapshots always using `\n`. It has a function somewhere in jest-snapshot which replaces all `\r\n` with `\n`. It probably should look for the OS line terminator as well, which would have avoided the issue in the first place.

**Comment by kentcdodds** [comment]
Thank you!
